databases:
  - name: malicious
    plan: free
    databaseName: malicious
    user: aitec_user

services:
  - type: web
    plan: free
    name: malicious
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn malicious.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: malicious
          property: connectionString
      - key: 6qrfZPFOdUbjfmCzY8hEZHsl1TIvTJqv
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4